### ISSUE TITLE
New cached responses generated for identical request

### ISSUE THREAD

**Issue by hanshenrik** [ijpiantanida/talkback#4]
Talkback keeps generating new cached responses after server restart even though the requests are identical. I thought the expected behaviour was that identical requests would cause the cached response to be returned.

<img width="935" alt="screen shot 2018-05-02 at 12 49 38" src="https://user-images.githubusercontent.com/3757042/39519532-643d9f8e-4e07-11e8-8c0b-b6de0c4187a0.png">

I'm guessing differences in `meta` and `res` shouldn't cause a new cached response to be generated?

**Comment by ijpiantanida** [comment]
You're right, identical `req` should match existing tapes. `meta` and `res` are not taken into account during the lookup.
Looking at the image I don't see any reason why the tape shouldn't match.

If you're willing to test, I published a new version `talkback@beta` that adds a `debug` option.
Set it to `true`, and it will print a lot of debug information.
For each saved tape, it will print the reason why it doesn't match a new request.

Thank you

**Comment by roypa** [comment]
I think I found the bug that makes this happen.

The response for this tape is not considered human readable (`meta.resHumanReadable=false`) because header value for "content-encoding" is gzip. The request is on the other side considered human readable, which is correct.

In the source file `tape.js` the method `static fromStore(raw, options)` checks on the var `raw.meta.resHumanReadable` for both `if` tests. The first `if` test is used for the request and has a bug is on line 22, where it should test the `raw.meta.reqHumanReadable` instead.

**Comment by ijpiantanida** [comment]
You're totally right @roypa! Thank you so much.

I just released `1.2.0` that fixes this issue.

**Comment by roypa** [comment]
Great!
Thank you so much for such a quick response.
